### ISSUE TITLE
wrong acceleration

### ISSUE THREAD

**Issue by Mur4ik** [fljot/TouchScrolling#1]
Если "схватить" вверху списка, протащить вниз, немного выждать и отпустить, то список все равно скролится, а по идее не должен, он должен остаться в том же положении, в котором его отпустили, т.к. ускорения уже нет никакого, т.е. его не разгоняли, а просто прокрутили в каком либо направлении.

Плюс вопрос на счет "обратного управления" скролом, например мне нужно прокрутить список до определенной позиции или элемента не трогая сам список, как это сделать? Например если список привязан к скроллбару и пользователь "толкает" не сам список, а воздействует на скроллбар, как следствие хочет увидеть перемещение списка.
Или при выборе элемента в другом списке нужно прокрутить сей компонент к определенной  позиции.

**Comment by fljot** [comment]
Что-то я с таким не сталкивался. Может оттрейсишь рассчёт скорости? Или видео запиши, хоть гляну. Вообще я сейчас немного переделываю архитектуру (см. соответствующую ветку), ну и заодно некоторые алгоритмические части тоже правлю. Так вот рассчёт скорости уже самую малость изменился. Скоро надеюсь привести примеры в рабочее состояние.

Твинь сам viewport, например, viewport.verticalScrollPosition любимым твинером. Аналогично и в новой архитектуре. Я намеренно не реализую этот функционал, т.к. он не относится к вопросу _ТАЧ_скроллинга.

**Comment by Mur4ik** [comment]
Да, на счет управления разобрался, нужно изменять просто horizontalScrollPosition или verticalScrollPosition.

А вот на счет ускорений, все же есть бага, например прокрутить вниз, не отпуская прокрутить вверх медленно, так чтоб без разгона, остановить и потом отпустить, содержимое контейнера скролится.
Могу минимальный пример выложить. http://screencast.com/t/qdo9ECjVF вот видео проблемы, когда курсор стоит на месте после прокрутки (отпустил), а список все же прокручивается.

**Comment by Mur4ik** [comment]
Плюс хотелось бы иметь возможность блокировать по направлению заранее, например указать что скрол только вертикальный, т.е. не пологаться на жесты в определении направления скрола, а именно самому указать.

**Comment by fljot** [comment]
Насчёт "блокировки заранее" — можно выставить scrollBounds с нулевой высотой/шириной для блокирование по соответствующим направлениям. И ещё поставить alwaysBounce_Vertical/Horizontal_ = false, чтобы оттягивания поперёк направления не было. Т.е. скажем, горизонтальный скролл без вертикального оттягивания-баунса делается так: scrollBounds = new Rectangle(left, top, width, 0); alwaysBounceVertical = false. И в твоём случае top = viewport.verticalScrollPosition. А после окончания скроллинга можно восстанавливать реальные scrollBounds, ну или что там надо по задаче. Надеюсь, понятно.

И сразу про "новое". Там по сути то же самое, только класс TouchScrollModel представляет собой исключительно модель тач-скроллинга. Оно ничего не знает о viewport'е. А scrollBounds там задаётся точно так же.

**Comment by Mur4ik** [comment]
Всё, я разобрался, проблема в "докручивании" после отпускания была в snappingDelegate, убрал его и всё стало работать как нужно. Спасибо за помощь.
